# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The cavern'd man
email: caverndman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mathematics, physics, music, programming and writing: this
  blog is about nothing of these.
baseurl: ""
url: "http://caverndman.github.io"
excerpt_separator: <!--break-->
paginate: 2

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate