# Site settings
title: The cavern'd man
email: caverndman@gmail.com
github_username: caverndman
description: >
  Mathematics, physics, music, programming and writing: this
  blog is about nothing of these.
baseurl: ""
url: "http://caverndman.github.io"
excerpt_separator: <!--break-->
paginate: 5

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist